baseURL = "https://morganlovett.com"
languageCode = "en-gb"
title = "Morgan Lovett"

# Site params

[params]
	author = "Morgan Lovett"
	description = "A place for my thoughts and findings"

# Main menu

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"

# Social links

[[params.social]]
  icon = "github"
  name = "GitHub"
  url = "https://github.com/mrlovett"
[[params.social]]
	icon = "twitter"
	name = "Twitter"
	url = "https://twitter.com/mlovettdev"

