baseURL = "https://morganlovett.com"
languageCode = "en-gb"

title = "Morgan Lovett"
description = "Hi, I'm Morgan! I'm a software developer from Wales, United Kingdom. I write about software development, travel and other things I find interesting."

disqusShortname = "morganlovett"

[social]
	twitter = 'mlovettdev'

# Site params

[params]
	title = "Morgan Lovett"
	description = "Hi, I'm Morgan! I'm a software developer from Wales, United Kingdom. I write about software development, travel and other things I find interesting."
	author = "Morgan Lovett"	
  googleAnalyticsId = "G-VX85Z40M5P"

# Main menu

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 2
#[[menu.main]]
#  identifier = "about"
#  name = "About"
#  url = "/about/"
#  weight = 3

# Social links

[[params.social]]
	icon = "twitter"
	name = "Twitter"
	url = "https://twitter.com/mlovettdev"
[[params.social]]
  icon = "github"
  name = "GitHub"
  url = "https://github.com/mrlovett"
[[params.social]]
  icon = "linkedin"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/morgan-l-1808531b0"
[[params.social]]
  icon = "rss"
  name = "RSS"
  url = "/index.xml"

[taxonomies]
  category = 'categories'
  tag = 'tags'
